# Generated by Django 4.2.7 on 2023-11-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, unique=True, verbose_name='ID чата'),
        ),
    ]
