# Generated by Django 4.2.7 on 2023-11-02 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.TextField(help_text='Действие — действие, которое, представляет из себя, привычка.', verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Признак публичности — привычки можно публиковать в общий доступ, чтобы другие пользователи могли брать в пример чужие привычки.', verbose_name='Признак публичности привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Пользователь — создатель привычки.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(default=1, help_text='Периодичность (по умолчанию ежедневная) — периодичность выполнения привычки для напоминания в днях.', verbose_name='Периодичность выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(help_text='Место — место, в котором необходимо выполнять привычку.', max_length=100, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='pleasant_habit',
            field=models.BooleanField(default=False, help_text='Признак приятной привычки — привычка, которую можно привязать к выполнению полезной привычки.', verbose_name='Признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='Связанная привычка — привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.TextField(blank=True, help_text='Вознаграждение — чем пользователь должен себя вознаградить после выполнения.', null=True, verbose_name='Вознаграждение за выполнение действия'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(help_text='Время — время, когда необходимо выполнять привычку.', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.IntegerField(help_text='Время на выполнение — время, которое предположительно потратит пользователь на выполнение привычки.', verbose_name='Время на выполнение, в секундах'),
        ),
    ]
