# Generated by Django 4.2.7 on 2023-11-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_habits', '0003_alter_habit_action_alter_habit_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка напоминания'),
        ),
    ]
